/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author rafael
 */
public class Nota_Fiscal_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Nota_Fiscal_GUI
     */
    public Nota_Fiscal_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Pessoa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFiscalNome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFiscalCpf = new javax.swing.JLabel();
        lblFiscalTelefone = new javax.swing.JLabel();
        lblFiscalPreco = new javax.swing.JLabel();
        lblFiscalPedido = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Nota Fiscal:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(29, 14, 337, 14);
        jPanel1.add(Pessoa);
        Pessoa.setBounds(29, 46, 75, 19);

        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(29, 71, 50, 14);
        jPanel1.add(lblFiscalNome);
        lblFiscalNome.setBounds(100, 50, 200, 20);

        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(29, 91, 23, 14);
        jPanel1.add(lblFiscalCpf);
        lblFiscalCpf.setBounds(100, 80, 200, 20);
        jPanel1.add(lblFiscalTelefone);
        lblFiscalTelefone.setBounds(100, 110, 220, 20);
        jPanel1.add(lblFiscalPreco);
        lblFiscalPreco.setBounds(20, 280, 270, 40);
        jPanel1.add(lblFiscalPedido);
        lblFiscalPedido.setBounds(20, 190, 300, 60);

        jLabel9.setText("Telefone:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(29, 111, 50, 14);

        jLabel8.setText("Pedido do cliente");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 170, 120, 14);

        jLabel10.setText("Preço");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 260, 120, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nota_Fiscal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nota_Fiscal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nota_Fiscal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nota_Fiscal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nota_Fiscal_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblFiscalCpf;
    public static javax.swing.JLabel lblFiscalNome;
    public static javax.swing.JLabel lblFiscalPedido;
    public static javax.swing.JLabel lblFiscalPreco;
    public static javax.swing.JLabel lblFiscalTelefone;
    // End of variables declaration//GEN-END:variables
}
